### ISSUE TITLE
'App is Already Installed' message

### ISSUE THREAD

**Issue by gb160** [getappbox/AppBox-iOSAppsWirelessInstallation#206]
Hi, im receiving that message when trying to update an app that I have installed, even though the version number is different that I can see in the Appbox dashboard.

Im using Appbox v2.9.1(1) on MacOS 11.0.1 

What information would you need to look into this?

Thanks

**Comment by vineetchoudhary** [comment]
Hi, Sorry for the late reply. I faced a similar issue once only deleting the existing app helped me. This is something iOS handles itself and AppBox doesn't play any role. Also, here a similar thread on apple dev forums but without any answer - https://developer.apple.com/forums/thread/666523

if you've AppBox links for both build (old version and new version) please share with me (if possible) at vineetchoudhary[at]live.in

**Comment by vineetchoudhary** [comment]
This issue has been closed because there has been no response to our request for more information from the author. With only the information that is currently on the issue, we don't have enough information to take action. Please reach out if you have or find the answers we need so that we can investigate further.
