### ISSUE TITLE
iOS install popup did not appear / Invalid URL. Please double check your app url / The app you were looking for is not available or accessible anymore

### ISSUE THREAD

**Issue by RedWizard89** [getappbox/AppBox-iOSAppsWirelessInstallation#255]
1. Open the link
2. Click on install latest version or install previous version
3. The screen "installation in progress" appear
4. The "dl.dropboxusercontent.com" popup not appear

The same app is not present on the device, any other app with the same bundle identifier is not present.
If I try to upload new link, this one give the error "Invalid URL. Please double-check your app URL."
The old update work, only the new one of today not work.

Edit: Dropbox add a string like "&rlkey=....." after dl=0, and I don't know why. I try with another Dropbox account and this string not appear.

- Device: iPhone 13 Pro
- OS: iOS 16.5
- Browser: Safari and Chrome

**Comment by 9folders-seokmin** [comment]
I'm having the same problem.

**Comment by vineetchoudhary** [comment]
Hi, Looks like Dropbox made some changes in URL sharing permissions. Please logout and login again to resolve the issue. If that doesn't work try to login with another account. I'll update here if I found something.

**Comment by vineetchoudhary** [comment]
Hi @RedWizard89 ,

We explored some options a few years back but non of them provide a direct download option(without any redirect).

Check this original issue about supporting other storage options - https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/issues/82

**Comment by vineetchoudhary** [comment]
[New response from the Dropbox team](https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/m-p/691491/highlight/true#M70437). I think they are going to support direct download via the `dl.dropboxusercontent.com` domain.

> Hi everyone, thank you for providing feedback in this post and bringing to our attention the issue with dl.dropbox.com and dl.dropboxusercontent.com not working for /scl/fi/ shared links. 
>
> Our engineering team is now aware of the issue and is actively working on a fix to restore the functionality that’s been mentioned. We expect this to be available within the week, and we’ll continue to keep you informed of the fix status in this forum post.
> 
> As we continue to roll out the centralized /scl/ link model in the future, we’ll continue to monitor this post and the community forum for any additional feedback.
> 
> Thank you again for the feedback and input in this post, and sincere apologies for the disruption the issue has caused.

**Comment by vineetchoudhary** [comment]
[Update from Dropbox team](https://www.dropboxforum.com/t5/Create-upload-and-share/Shared-Link-quot-scl-quot-to-quot-s-quot/m-p/691764/highlight/true#M70497) - 

> Hi everyone,
>
> As an update on the dropboxusercontent issue, the fix is now available. For your shared links that look like "www.dropbox.com/scl/fi/...",  you should now be able to generate a direct download of the content using either "dl.dropbox.com/scl/fi/..." or "dl.dropboxusercontent.com/scl/fi/..."

**But this is still not working for the share URL generated via Dropbox SDK. Which AppBox use to generate share URLs automatically.**

**Comment by vineetchoudhary** [comment]
For now, created an incident on the status page. Also, you'll see a different error message on the AppBox Installation Website instead of the invalid URL message (thanks @BodyBookApps).

![Screenshot 2023-06-15 at 10 22 31 AM](https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/8479436/1e7cd6e6-db33-44f1-8f71-c6e3b406d425)


![Screenshot 2023-06-15 at 10 22 45 AM](https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/8479436/0e60e995-52a4-4067-9cc4-30432aceca1d)

**Comment by radubogdan2k** [comment]
@vineetchoudhary Thanks for the quick reply, I sent the email

**Comment by vineetchoudhary** [comment]
Thanks @radubogdan2k, These percentage encoded URL was completely out of my mind. I deployed a fix on the installation page for percentage encoded URLs. All of your existing links should work fine now. I'll keep your app link for future testing before making any deployment to production.

<img width="771" alt="Screenshot 2023-06-15 at 2 44 41 PM" src="https://github.com/getappbox/AppBox-iOSAppsWirelessInstallation/assets/8479436/6031e09f-9c48-4ed1-a632-4a3f71da33ee">

**Comment by radubogdan2k** [comment]
@vineetchoudhary That's awesome, thank you!

**Comment by BodyBookApps** [comment]
Vineet Thank you for taking action.  This message is better as it gives a solution to solve the problem. Nice work.  Best wishes Sent from my iPhoneOn Jun 15, 2023, at 5:12 AM, Vineet Choudhary ***@***.***> wrote:﻿
Hi @radubogdan2k, It should not affect the existing applications. Can you please share the application link here - vineetchoudhary[at]live.in

**Comment by toseefkhilji** [comment]
@vineetchoudhary : We faced the same issue.
I tried with another old account, and it worked! 🎉🎊

Thank you.
But for the future, we need to check other options as well. Github private repo?

**Comment by vineetchoudhary** [comment]
Hi all,

I create a middleware service (`install.getappbox.com`) to handle the new Dropbox share URL. Can you guys please check if your existing app (with old or new format share URL) is working fine? To check, replace the `web.getappbox.com` installation web page domain with `web2.getappbox.com`. After this try to install your app and check if you are able to install it without any issues. 

So, if your app installation URL is https://web.getappbox.com/?url=/s/xxxxxxxx/appinfo.json then for the new web app it will be https://web2.getappbox.com/?url=/s/xxxxxxxx/appinfo.json.

Same for the new format URL. If the URL is https://web.getappbox.com/?url=/scl/fi/xxxxxxx/appinfo.json?rlkey=xxxxxx then for the new web app it will be https://web2.getappbox.com/?url=/scl/fi/xxxxxxx/appinfo.json?rlkey=xxxxxx

Monday morning (IST) I'll push these changes to prod installation web page (web.getappbox.com).

---

With this new middleware, you will see `install.getappbox.com would like to install "App"` instead of `dl.dropboxusercontent.com`. Your file is still on Dropbox but the installation page access it via middleware to remove query parameters. because iOS `itms-services` doesn't allow query parameters in the `manifest.plist` file. This middleware service code is available here - https://github.com/getappbox/install-helper.

---

If you are not able to install the app let me know. Or please share the application link here - vineetchoudhary[at]live.in

**Comment by vineetchoudhary** [comment]
Hi all,

All the above changes in available in prod. You should be able to install the app with the new Dropbox share URL format. I'm closing this issue. Please feel free to reopen it or create new issue if you still face some issue.

**Note** - All new format share URL generated in the month of June is not supported. New format share URL generated after the 1st of July will work fine.
